// Generated by CoffeeScript 1.6.3
(function() {
  var Robot, TextMessage, chai, expect, mocha;

  Robot = require("hubot/src/robot");

  TextMessage = require("hubot/src/message").TextMessage;

  chai = require('chai');

  mocha = require('mocha');

  expect = chai.expect;

  describe('a hubot doing his thing', function() {
    var robot, user;
    user = null;
    robot = null;
    beforeEach(function(done) {
      robot = new Robot(null, 'mock-adapter', true, 'TestHubot');
      robot.adapter.on('connected', function() {
        require("../angry")(robot);
        user = robot.brain.userForId("1", {
          name: "mocha",
          room: "#mocha"
        });
        return done();
      });
      return robot.run();
    });
    afterEach(function(done) {
      robot.shutdown();
      return done();
    });
    it("responds when it hears angry", function(done) {
      robot.adapter.on("reply", function(envelope, strings) {
        expect(strings[0]).to.be.a('string');
        return done();
      });
      return robot.adapter.receive(new TextMessage(user, "angry"));
    });
    return it("responds when asked for an animal lod", function(done) {
      robot.adapter.on("reply", function(envelope, strings) {
        expect(strings[0]).to.be.a('string');
        return done();
      });
      return robot.adapter.receive(new TextMessage(user, "animal lod"));
    });
  });

}).call(this);
